### ISSUE TITLE
Setup cronjob for taxa refresh

### ISSUE THREAD

**Issue by BenMerSci** [BiodiversiteQuebec/atlas-db#129]
Setup cronjob to refresh the taxonomy pipeline:

- [ ] Cronjob to partially refresh the taxo:
       - Should

**Comment by BenMerSci** [comment]
Do we really need cronjob for the taxa now? Since we only refresh taxa on staging when ready to merge to prod (so taxa refresh is only done prior when we actually need to refresh it)

**Comment by vcameron1** [comment]
Given the new workflow I agree that it is an unnecessary feature and manually launching the bash script should be enough
